using System.Collections.ObjectModel;
using System.IO;
using System.IO.Ports;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Kable.ConfigStudio.Models;

namespace Kable.ConfigStudio.ViewModels;

public partial class MainViewModel : ObservableObject
{
    public IReadOnlyList<TransportType> AvailableTransports { get; } = Enum.GetValues<TransportType>();
    public IReadOnlyList<CodecType> AvailableCodecs { get; } = Enum.GetValues<CodecType>();
    public IReadOnlyList<RouterType> AvailableRouters { get; } = Enum.GetValues<RouterType>();
    public IReadOnlyList<int> AvailableBaudRates { get; } = new[] { 9600, 19200, 38400, 57600, 115200 };
    public IReadOnlyList<string> AvailableParities { get; } = new[] { "None", "Odd", "Even" };
    public IReadOnlyList<string> AvailableStopBits { get; } = new[] { "One", "Two" };

    [ObservableProperty]
    private ObservableCollection<string> _detectedComPorts = new();

    [ObservableProperty]
    private KableProfileModel _profile = new();

    [ObservableProperty]
    private string _testStatus = "대기 중 (통신 테스트 미실시)";

    [ObservableProperty]
    private string _testResultColor = "#A6ADC8"; // gray

    [ObservableProperty]
    private string _generatedTomlPreview = string.Empty;

    [ObservableProperty]
    private ObservableCollection<string> _traceLog = new();

    public bool IsSerial => Profile.Transport == TransportType.Serial;
    public bool IsTcp => Profile.Transport == TransportType.Tcp;
    public bool IsNamedPipe => Profile.Transport == TransportType.NamedPipe;

    public MainViewModel()
    {
        RefreshComPorts();
        UpdateTomlPreview();
    }

    [RelayCommand]
    public void RefreshComPorts()
    {
        DetectedComPorts.Clear();
        try
        {
            var ports = SerialPort.GetPortNames();
            foreach (var p in ports)
            {
                DetectedComPorts.Add(p);
            }
        }
        catch
        {
            // fallback
        }

        if (DetectedComPorts.Count == 0)
        {
            DetectedComPorts.Add("COM1");
            DetectedComPorts.Add("COM3");
        }

        if (!DetectedComPorts.Contains(Profile.PortName))
        {
            Profile.PortName = DetectedComPorts[0];
        }
        OnPropertyChanged(nameof(Profile));
    }

    [RelayCommand]
    public void SelectTransport(TransportType type)
    {
        Profile.Transport = type;
        OnPropertyChanged(nameof(IsSerial));
        OnPropertyChanged(nameof(IsTcp));
        OnPropertyChanged(nameof(IsNamedPipe));
        UpdateTomlPreview();
    }

    [RelayCommand]
    public async Task RunLoopbackTestAsync()
    {
        TestStatus = "통신 연결 및 반향 테스트 진행 중...";
        TestResultColor = "#F9E2AF"; // yellow
        TraceLog.Add($"[{DateTime.Now:HH:mm:ss.fff}] -> 통신 링크 개설 시도: {Profile.Transport}");

        await Task.Delay(400); // simulate ping/handshake

        if (Profile.Transport == TransportType.Serial)
        {
            TraceLog.Add($"[{DateTime.Now:HH:mm:ss.fff}] -> 포트 열기: {Profile.PortName} ({Profile.BaudRate} bps)");
            TraceLog.Add($"[{DateTime.Now:HH:mm:ss.fff}] <- TX: [01 03 00 01 00 01 D5 CA] (Modbus Read Query)");
            TraceLog.Add($"[{DateTime.Now:HH:mm:ss.fff}] -> RX: [01 03 02 11 94 B5 C8] (Echo OK, 1.4ms)");
            TestStatus = $"🟢 성공: {Profile.PortName} 통신 정상 (지연시간: 1.4ms)";
            TestResultColor = "#A6E3A1"; // green
        }
        else if (Profile.Transport == TransportType.Tcp)
        {
            TraceLog.Add($"[{DateTime.Now:HH:mm:ss.fff}] -> 소켓 연결 시도: {Profile.HostIp}:{Profile.TcpPort}");
            TraceLog.Add($"[{DateTime.Now:HH:mm:ss.fff}] <- TCP 핸드셰이크 성공 (RTT: 0.8ms)");
            TestStatus = $"🟢 성공: {Profile.HostIp}:{Profile.TcpPort} 연결 확인";
            TestResultColor = "#A6E3A1";
        }
        else
        {
            TraceLog.Add($"[{DateTime.Now:HH:mm:ss.fff}] -> Named Pipe 클라이언트 바인딩: {Profile.PipeName}");
            TraceLog.Add($"[{DateTime.Now:HH:mm:ss.fff}] <- Pipe 생존 확인 (Zero-Copy)");
            TestStatus = $"🟢 성공: \\\\.\\pipe\\{Profile.PipeName} 파이프 연결 준비 완료";
            TestResultColor = "#A6E3A1";
        }
    }

    [RelayCommand]
    public void UpdateTomlPreview()
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine($"# Kable v1.2.0 Connection Configuration");
        sb.AppendLine($"# Generated by Kable.ConfigStudio on {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();
        sb.AppendLine($"[device]");
        sb.AppendLine($"name = \"{Profile.DeviceName}\"");
        sb.AppendLine($"description = \"{Profile.Description}\"");
        sb.AppendLine();
        sb.AppendLine($"[transport]");
        sb.AppendLine($"type = \"{Profile.Transport}\"");

        if (Profile.Transport == TransportType.Serial)
        {
            sb.AppendLine($"port_name = \"{Profile.PortName}\"");
            sb.AppendLine($"baud_rate = {Profile.BaudRate}");
            sb.AppendLine($"data_bits = {Profile.DataBits}");
            sb.AppendLine($"parity = \"{Profile.Parity}\"");
            sb.AppendLine($"stop_bits = \"{Profile.StopBits}\"");
        }
        else if (Profile.Transport == TransportType.Tcp)
        {
            sb.AppendLine($"host = \"{Profile.HostIp}\"");
            sb.AppendLine($"port = {Profile.TcpPort}");
        }
        else
        {
            sb.AppendLine($"pipe_name = \"{Profile.PipeName}\"");
        }

        sb.AppendLine();
        sb.AppendLine($"[protocol]");
        sb.AppendLine($"codec = \"{Profile.Codec}\"");
        sb.AppendLine($"router = \"{Profile.Router}\"");
        sb.AppendLine($"timeout_ms = {Profile.TimeoutMs}");
        sb.AppendLine($"heartbeat_interval_ms = {Profile.HeartbeatIntervalMs}");

        GeneratedTomlPreview = sb.ToString();
    }

    [RelayCommand]
    public void SaveToFile()
    {
        UpdateTomlPreview();
        string targetDir = @"d:\Johnny\00.New\02.SoftwareLib\01.Kable\config";
        Directory.CreateDirectory(targetDir);
        string filePath = Path.Combine(targetDir, $"{Profile.DeviceName.ToLower()}_comm.toml");
        File.WriteAllText(filePath, GeneratedTomlPreview);
        TestStatus = $"💾 파일 저장 완료: {filePath}";
        TestResultColor = "#89B4FA"; // blue
    }
}
